<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.nrg</groupId>
        <artifactId>test_dependencies</artifactId>
        <version>3.0-SNAPSHOT</version>
    </parent>

    <artifactId>xnat_rest_tests</artifactId>
    <version>1.2-SNAPSHOT</version>

    <name>REST-based XNAT Tests</name>
    <description>Runs a suite of REST tests on an XNAT server.</description>

    <developers>
        <developer>
            <id>cmoore01</id>
            <name>Charlie Moore</name>
            <email>moore.c@wustl.edu</email>
        </developer>
        <developer>
            <id>rick</id>
            <name>Rick Herrick</name>
        </developer>
        <developer>
            <id>tim</id>
            <name>Tim Olsen</name>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://bitbucket.org/xnatdev/xnat_rest_tests</connection>
        <url>scm:git:https://bitbucket.org/xnatdev/xnat_rest_tests</url>
    </scm>

    <properties>
        <nrg_test.version>2.1-SNAPSHOT</nrg_test.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>nrg_test</artifactId>
            <version>${nrg_test.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nrg.xnat</groupId>
            <artifactId>web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.nrg.xdat</groupId>
            <artifactId>core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.nrg.xnat</groupId>
            <artifactId>xnat-data-models</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.nrg.dicom</groupId>
            <artifactId>mizer</artifactId>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.nrg</groupId>
            <artifactId>transaction</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-configuration</groupId>
            <artifactId>commons-configuration</artifactId>
        </dependency>

    </dependencies>

    <repositories>
        <repository>
            <id>org.nrg.xnat.maven.libraries.release</id>
            <name>XNAT Maven Release Libraries</name>
            <url>https://nrgxnat.jfrog.io/nrgxnat/libs-release</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>org.nrg.xnat.maven.libraries.snapshot</id>
            <name>XNAT Maven Snapshot Libraries</name>
            <url>https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
        <repository>
            <id>org.nrg.maven.artifacts.remote</id>
            <name>XNAT Remote Maven Repo</name>
            <url>https://nrgxnat.jfrog.io/nrgxnat/remote-repos</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
